name: Monitoramento de Barragens

on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora
  workflow_dispatch: # Botão para rodar manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install requests pandas

      - name: Rodar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TZ: "America/Sao_Paulo" # Define o fuso horário da máquina virtual
        run: python main.py
