name: Monitoramento Horario de Barragens

on:
  schedule:
    # Isso faz o script rodar no minuto 0 de cada hora
    - cron: '0 * * * *'
  
  # Permite que você clique em um botão para testar na hora que quiser
  workflow_dispatch: 

jobs:
  executar_monitoramento:
    runs-on: ubuntu-latest
    
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Instalar o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar as bibliotecas (Pandas e Requests)
        run: |
          pip install -r requirements.txt

      - name: Rodar o script de monitoramento
        env:
          # Aqui o GitHub pega as senhas que voce vai cadastrar no Settings
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
